// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/user/v1/error.proto

package errs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Err int32

const (
	Err_OK Err = 0
	// zh: 用户不存在
	// en: User not found
	Err_UserNotFound Err = 10020001
	// zh: 用户被封禁
	// en: User banned
	Err_UserBanned Err = 10020002
	// zh: 密码错误
	// en: Invalid password
	Err_InvalidPassword Err = 10020003
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0:        "OK",
		10020001: "UserNotFound",
		10020002: "UserBanned",
		10020003: "InvalidPassword",
	}
	Err_value = map[string]int32{
		"OK":              0,
		"UserNotFound":    10020001,
		"UserBanned":      10020002,
		"InvalidPassword": 10020003,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_v1_error_proto_enumTypes[0].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_proto_user_v1_error_proto_enumTypes[0]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_proto_user_v1_error_proto protoreflect.FileDescriptor

var file_proto_user_v1_error_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x2a, 0x4d, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0xa1, 0xc9, 0xe3, 0x04, 0x12, 0x11, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x10, 0xa2, 0xc9, 0xe3, 0x04, 0x12, 0x16, 0x0a, 0x0f, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0xa3, 0xc9, 0xe3, 0x04,
	0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72,
	0x72, 0x73, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var (
	file_proto_user_v1_error_proto_rawDescOnce sync.Once
	file_proto_user_v1_error_proto_rawDescData []byte
)

func file_proto_user_v1_error_proto_rawDescGZIP() []byte {
	file_proto_user_v1_error_proto_rawDescOnce.Do(func() {
		file_proto_user_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_v1_error_proto_rawDesc), len(file_proto_user_v1_error_proto_rawDesc)))
	})
	return file_proto_user_v1_error_proto_rawDescData
}

var file_proto_user_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_v1_error_proto_goTypes = []any{
	(Err)(0), // 0: user.Err
}
var file_proto_user_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_v1_error_proto_init() }
func file_proto_user_v1_error_proto_init() {
	if File_proto_user_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_v1_error_proto_rawDesc), len(file_proto_user_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_v1_error_proto_goTypes,
		DependencyIndexes: file_proto_user_v1_error_proto_depIdxs,
		EnumInfos:         file_proto_user_v1_error_proto_enumTypes,
	}.Build()
	File_proto_user_v1_error_proto = out.File
	file_proto_user_v1_error_proto_goTypes = nil
	file_proto_user_v1_error_proto_depIdxs = nil
}
