// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/user/v1/error.proto

package errs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Err int32

const (
	Err_OK Err = 0
	// zh: 系统繁忙
	// en: System busy
	Err_SystemBusy Err = 10000001
	// zh: 用户不存在
	// en: User not found
	Err_UserNotFound Err = 10020001
	// zh: 用户被封禁
	// en: User banned
	Err_UserBanned Err = 10020002
	// zh: 用户已存在
	// en: User already exists
	Err_UserAlreadyExists Err = 10020003
	// zh: 用户在注销中
	// en: User is deleting
	Err_UserDeleting Err = 10020004
	// zh: 登录失败
	// en: login failed error
	Err_LoginFailed Err = 10020005
	// zh: 用户名或密码错误
	// en: Username or password error
	Err_UsernameOrPasswordErr Err = 10020009
	// zh: 密码错误
	// en: Invalid password
	Err_InvalidPassword Err = 10020010
	// zh: 密码格式不符合
	// en: Invalid password format
	Err_InvalidPasswordFormat Err = 10020012
	// zh: 新密码与旧密码相同
	// en: New Password Same As Old
	Err_NewPasswordSameAsOld Err = 10020013
	// zh: 验证码加载失败
	// en: Captcha load failed
	Err_CaptchaLoad Err = 10020020
	// zh: 验证码错误
	// en: Captcha valid failed
	Err_CaptchaValidFailed Err = 10020021
	// zh: 令牌格式错误
	// en: Token format error
	Err_TokenMalformed Err = 10020022
	// zh: 令牌无效
	// en: Token invalid
	Err_TokenUnverifiable Err = 10020023
	// zh: 令牌过期
	// en: Token expired
	Err_TokenExpired Err = 10020024
	// zh: 令牌主题无效
	// en: Token subject invalid
	Err_TokenInvalidSubject Err = 10020025
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0:        "OK",
		10000001: "SystemBusy",
		10020001: "UserNotFound",
		10020002: "UserBanned",
		10020003: "UserAlreadyExists",
		10020004: "UserDeleting",
		10020005: "LoginFailed",
		10020009: "UsernameOrPasswordErr",
		10020010: "InvalidPassword",
		10020012: "InvalidPasswordFormat",
		10020013: "NewPasswordSameAsOld",
		10020020: "CaptchaLoad",
		10020021: "CaptchaValidFailed",
		10020022: "TokenMalformed",
		10020023: "TokenUnverifiable",
		10020024: "TokenExpired",
		10020025: "TokenInvalidSubject",
	}
	Err_value = map[string]int32{
		"OK":                    0,
		"SystemBusy":            10000001,
		"UserNotFound":          10020001,
		"UserBanned":            10020002,
		"UserAlreadyExists":     10020003,
		"UserDeleting":          10020004,
		"LoginFailed":           10020005,
		"UsernameOrPasswordErr": 10020009,
		"InvalidPassword":       10020010,
		"InvalidPasswordFormat": 10020012,
		"NewPasswordSameAsOld":  10020013,
		"CaptchaLoad":           10020020,
		"CaptchaValidFailed":    10020021,
		"TokenMalformed":        10020022,
		"TokenUnverifiable":     10020023,
		"TokenExpired":          10020024,
		"TokenInvalidSubject":   10020025,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_v1_error_proto_enumTypes[0].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_proto_user_v1_error_proto_enumTypes[0]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_proto_user_v1_error_proto protoreflect.FileDescriptor

const file_proto_user_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x19proto/user/v1/error.proto\x12\x04user*\x8d\x03\n" +
	"\x03Err\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\n" +
	"SystemBusy\x10\x81\xad\xe2\x04\x12\x13\n" +
	"\fUserNotFound\x10\xa1\xc9\xe3\x04\x12\x11\n" +
	"\n" +
	"UserBanned\x10\xa2\xc9\xe3\x04\x12\x18\n" +
	"\x11UserAlreadyExists\x10\xa3\xc9\xe3\x04\x12\x13\n" +
	"\fUserDeleting\x10\xa4\xc9\xe3\x04\x12\x12\n" +
	"\vLoginFailed\x10\xa5\xc9\xe3\x04\x12\x1c\n" +
	"\x15UsernameOrPasswordErr\x10\xa9\xc9\xe3\x04\x12\x16\n" +
	"\x0fInvalidPassword\x10\xaa\xc9\xe3\x04\x12\x1c\n" +
	"\x15InvalidPasswordFormat\x10\xac\xc9\xe3\x04\x12\x1b\n" +
	"\x14NewPasswordSameAsOld\x10\xad\xc9\xe3\x04\x12\x12\n" +
	"\vCaptchaLoad\x10\xb4\xc9\xe3\x04\x12\x19\n" +
	"\x12CaptchaValidFailed\x10\xb5\xc9\xe3\x04\x12\x15\n" +
	"\x0eTokenMalformed\x10\xb6\xc9\xe3\x04\x12\x18\n" +
	"\x11TokenUnverifiable\x10\xb7\xc9\xe3\x04\x12\x13\n" +
	"\fTokenExpired\x10\xb8\xc9\xe3\x04\x12\x1a\n" +
	"\x13TokenInvalidSubject\x10\xb9\xc9\xe3\x04B\x10Z\x0e./user/v1/errsb\x06proto3"

var (
	file_proto_user_v1_error_proto_rawDescOnce sync.Once
	file_proto_user_v1_error_proto_rawDescData []byte
)

func file_proto_user_v1_error_proto_rawDescGZIP() []byte {
	file_proto_user_v1_error_proto_rawDescOnce.Do(func() {
		file_proto_user_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_v1_error_proto_rawDesc), len(file_proto_user_v1_error_proto_rawDesc)))
	})
	return file_proto_user_v1_error_proto_rawDescData
}

var file_proto_user_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_v1_error_proto_goTypes = []any{
	(Err)(0), // 0: user.Err
}
var file_proto_user_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_v1_error_proto_init() }
func file_proto_user_v1_error_proto_init() {
	if File_proto_user_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_v1_error_proto_rawDesc), len(file_proto_user_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_v1_error_proto_goTypes,
		DependencyIndexes: file_proto_user_v1_error_proto_depIdxs,
		EnumInfos:         file_proto_user_v1_error_proto_enumTypes,
	}.Build()
	File_proto_user_v1_error_proto = out.File
	file_proto_user_v1_error_proto_goTypes = nil
	file_proto_user_v1_error_proto_depIdxs = nil
}
