name: admin-service
version: '0.0.1'
env: dev
timeFormat: '2006-01-02 15:04:05'
configs:
  - ./db.yaml
  - ./logger.yaml
  - ./redis.yaml
server:
  http:
    addr: '0.0.0.0:8080'
    timeout: 1s
  rpc:
    addr: '0.0.0.0:9080'
    timeout: 1s
security:
  ciphertext:
    isCiphertext: false
    cipherKey: YpC5wIRf4ZuMvd4f
  jwt:
    secret: YpC5wIRf4ZuMvd4f
    issuer: gogo-admin
    cacheKeyPrefix: "admin:login_token"
# 业务相关
service:
  errAttemptLimit: 5

# ====================================
# registry
registry:
  addr: '127.0.0.1:2379'