// Code generated by error message generator. DO NOT EDIT.

package v1

// ErrorMessageMap 存储错误码及其多语言信息
var ErrorMessageMap = map[int32]map[string]string{
	10020001: {
		"zh": "用户不存在",
		"en": "User not found",
	},
	10020002: {
		"zh": "用户被封禁",
		"en": "User banned",
	},
	10020003: {
		"zh": "密码错误",
		"en": "Invalid password",
	},
}

// GetErrorMessage 获取错误信息
func GetErrorMessage(code int32, lang string) string {
	if translations, exists := ErrorMessageMap[code]; exists {
		if msg, ok := translations[lang]; ok {
			return msg
		}
		return translations["zh"] // 默认返回中文
	}
	return "未知错误"
}
