// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPoint = "user_points"

// UserPoint 用户积分记录表（支持积分有效期）
type UserPoint struct {
	ID          string     `gorm:"column:id;type:varchar(36);primaryKey;comment:积分记录ID（UUID）" json:"id"`                                              // 积分记录ID（UUID）
	UserID      string     `gorm:"column:user_id;type:varchar(36);not null;index:idx_user_id,priority:1;comment:用户ID（逻辑关联 users(id)）" json:"user_id"` // 用户ID（逻辑关联 users(id)）
	Points      int32      `gorm:"column:points;type:int;not null;comment:积分变动数量（可正可负）" json:"points"`                                                // 积分变动数量（可正可负）
	Reason      int32      `gorm:"column:reason;type:tinyint;not null;comment:积分变动原因 (1=购买, 2=签到, 3=邀请, 4=退款, 5=管理员调整, 6=其他)" json:"reason"`          // 积分变动原因 (1=购买, 2=签到, 3=邀请, 4=退款, 5=管理员调整, 6=其他)
	Description *string    `gorm:"column:description;type:varchar(255);comment:变动描述" json:"description"`                                              // 变动描述
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                         // 创建时间
	ExpiredAt   *time.Time `gorm:"column:expired_at;type:timestamp;index:idx_expired_at,priority:1;comment:积分过期时间（NULL表示永久有效）" json:"expired_at"`     // 积分过期时间（NULL表示永久有效）
}

// TableName UserPoint's table name
func (*UserPoint) TableName() string {
	return TableNameUserPoint
}
