// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserDeletionRequest = "user_deletion_requests"

// UserDeletionRequest 用户注销请求表
type UserDeletionRequest struct {
	ID          string     `gorm:"column:id;type:varchar(36);primaryKey;comment:注销请求ID（UUID）" json:"id"`                                                              // 注销请求ID（UUID）
	UserID      string     `gorm:"column:user_id;type:varchar(36);not null;uniqueIndex:user_id,priority:1;comment:用户ID（关联 users(id)）" json:"user_id"`                 // 用户ID（关联 users(id)）
	RequestedAt *time.Time `gorm:"column:requested_at;type:timestamp;index:idx_requested_at,priority:1;default:CURRENT_TIMESTAMP;comment:注销请求时间" json:"requested_at"` // 注销请求时间
}

// TableName UserDeletionRequest's table name
func (*UserDeletionRequest) TableName() string {
	return TableNameUserDeletionRequest
}
