// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserProfile = "user_profiles"

// UserProfile 用户详情表
type UserProfile struct {
	UserID    string     `gorm:"column:user_id;type:varchar(36);primaryKey;comment:用户ID（逻辑关联 users(id)）" json:"user_id"`    // 用户ID（逻辑关联 users(id)）
	FullName  *string    `gorm:"column:full_name;type:varchar(100);comment:用户真实姓名" json:"full_name"`                        // 用户真实姓名
	Gender    *int32     `gorm:"column:gender;type:tinyint;comment:性别 (0=未知, 1=男, 2=女)" json:"gender"`                      // 性别 (0=未知, 1=男, 2=女)
	BirthDate *time.Time `gorm:"column:birth_date;type:date;comment:生日" json:"birth_date"`                                  // 生日
	AvatarURL *string    `gorm:"column:avatar_url;type:varchar(255);comment:头像URL" json:"avatar_url"`                       // 头像URL
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName UserProfile's table name
func (*UserProfile) TableName() string {
	return TableNameUserProfile
}
