// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAddress = "user_addresses"

// UserAddress 用户地址表
type UserAddress struct {
	ID         string     `gorm:"column:id;type:varchar(36);primaryKey;comment:地址ID（UUID）" json:"id"`                                                // 地址ID（UUID）
	UserID     string     `gorm:"column:user_id;type:varchar(36);not null;index:idx_user_id,priority:1;comment:用户ID（逻辑关联 users(id)）" json:"user_id"` // 用户ID（逻辑关联 users(id)）
	Recipient  string     `gorm:"column:recipient;type:varchar(100);not null;comment:收件人姓名" json:"recipient"`                                        // 收件人姓名
	Phone      string     `gorm:"column:phone;type:varchar(20);not null;comment:联系电话" json:"phone"`                                                  // 联系电话
	Province   string     `gorm:"column:province;type:varchar(50);not null;comment:省份" json:"province"`                                              // 省份
	City       string     `gorm:"column:city;type:varchar(50);not null;comment:城市" json:"city"`                                                      // 城市
	District   string     `gorm:"column:district;type:varchar(50);not null;comment:区/县" json:"district"`                                             // 区/县
	Detail     string     `gorm:"column:detail;type:varchar(255);not null;comment:详细地址" json:"detail"`                                               // 详细地址
	PostalCode *string    `gorm:"column:postal_code;type:varchar(10);comment:邮政编码" json:"postal_code"`                                               // 邮政编码
	IsDefault  *bool      `gorm:"column:is_default;type:tinyint(1);comment:是否为默认地址" json:"is_default"`                                               // 是否为默认地址
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                         // 创建时间
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                         // 更新时间
}

// TableName UserAddress's table name
func (*UserAddress) TableName() string {
	return TableNameUserAddress
}
