// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserLoginSuccessLog = "user_login_success_log"

// UserLoginSuccessLog 用户登录成功日志表
type UserLoginSuccessLog struct {
	ID                uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:日志主键" json:"id"`                                                                                                                      // 日志主键
	UserID            string    `gorm:"column:user_id;type:varchar(64);not null;index:idx_user_login,priority:1;comment:用户ID" json:"user_id"`                                                                                                     // 用户ID
	Username          string    `gorm:"column:username;type:varchar(64);not null;comment:登录用户名" json:"username"`                                                                                                                                  // 登录用户名
	LoginTime         time.Time `gorm:"column:login_time;type:datetime(6);not null;index:idx_ip_time,priority:2;index:idx_risk_time,priority:2;index:idx_user_login,priority:2;default:CURRENT_TIMESTAMP(6);comment:登录时间(含毫秒)" json:"login_time"` // 登录时间(含毫秒)
	ClientIP          string    `gorm:"column:client_ip;type:varchar(48);not null;index:idx_ip_time,priority:1;comment:客户端IP(支持IPv6)" json:"client_ip"`                                                                                           // 客户端IP(支持IPv6)
	UserAgent         *string   `gorm:"column:user_agent;type:varchar(512);comment:浏览器UA原始值" json:"user_agent"`                                                                                                                                   // 浏览器UA原始值
	LoginChannel      uint32    `gorm:"column:login_channel;type:tinyint unsigned;not null;comment:登录渠道(0=Web,1=Android,...)" json:"login_channel"`                                                                                               // 登录渠道(0=Web,1=Android,...)
	GeoLocation       *string   `gorm:"column:geo_location;type:varchar(100);comment:地理定位(格式：国家-省份-城市)" json:"geo_location"`                                                                                                                      // 地理定位(格式：国家-省份-城市)
	AuthMethod        string    `gorm:"column:auth_method;type:varchar(20);not null;default:password;comment:认证方式" json:"auth_method"`                                                                                                            // 认证方式
	DeviceFingerprint *string   `gorm:"column:device_fingerprint;type:char(32);index:idx_device,priority:1;comment:设备指纹MD5" json:"device_fingerprint"`                                                                                            // 设备指纹MD5
	RiskLevel         int32     `gorm:"column:risk_level;type:tinyint;not null;index:idx_risk_time,priority:1;comment:风险等级(0=正常,1=可疑,2=高危)" json:"risk_level"`                                                                                    // 风险等级(0=正常,1=可疑,2=高危)
}

// TableName UserLoginSuccessLog's table name
func (*UserLoginSuccessLog) TableName() string {
	return TableNameUserLoginSuccessLog
}
