app:
  name: gateway
  version: v1.0.0
  server:
    http:
      addr: 0.0.0.0:8000
      timeout: 1s
    rpc:
      addr: 0.0.0.0:9000
      timeout: 1s
  serviceKV: # 应用的业务自定义配置
    authenticationKey: xxx-xxx-xx