app:
  name: main-service
  version: v1.0.0
  server:
    http:
      addr: 0.0.0.0:8001
      timeout: 1s
    rpc:
      addr: 0.0.0.0:9001
      timeout: 1s
  serviceKV: # 应用的业务自定义配置
    authenticationKey: xxx-xxx-xx
data:
  database:
    driver: mysql
    source: root:root@tcp(mysql-svc:3306)/gogo_main